Notify when files are updated on S3, but without @channel
This was suggested in conversation on Slack about notifications.  It
seems useful to keep tabs on what the automation is doing, but won't
cause alerts with @channel like we use for new records.

Unlike for notify-on-gisaid-change, it is not an error condition if
upload-to-s3 can't notify Slack.

diff --git a/bin/upload-to-s3 b/bin/upload-to-s3
--- a/bin/upload-to-s3
+++ b/bin/upload-to-s3
@@ -15,6 +15,10 @@ echo "$dst_hash $dst"
 if [[ $src_hash != $dst_hash ]]; then
     echo "Uploading $src → $dst"
     aws s3 cp "$src" "$dst"
+
+    if ! "$bin"/notify-slack "Updated $dst available."; then
+        echo "Notifying Slack failed, but exiting with success anyway."
+    fi
 else
     echo "Files are identical, skipping upload"
 fi
