upload-to-s3: Refactor logic into main function
Refactor `upload-to-s3` to move the file diffing, upload and Slack
notification logic into a `main()` function. This will allow us to use
`case` to analyze optional arguments in a follow-up commit. This diff is
best viewed with `--ignore-all-space`.

diff --git a/bin/upload-to-s3 b/bin/upload-to-s3
--- a/bin/upload-to-s3
+++ b/bin/upload-to-s3
@@ -6,19 +6,23 @@ bin="$(dirname "$0")"
 src="${1:?A source file is required as the first argument.}"
 dst="${2:?A destination s3:// URL is required as the second argument.}"
 
-src_hash="$("$bin/sha256sum" < "$src")"
-dst_hash="$("$bin/sha256sum" < <(aws s3 cp "$dst" -))"
+main() {
+    src_hash="$("$bin/sha256sum" < "$src")"
+    dst_hash="$("$bin/sha256sum" < <(aws s3 cp "$dst" -))"
 
-echo "$src_hash $src"
-echo "$dst_hash $dst"
+    echo "$src_hash $src"
+    echo "$dst_hash $dst"
 
-if [[ $src_hash != $dst_hash ]]; then
-    echo "Uploading $src → $dst"
-    aws s3 cp "$src" "$dst"
+    if [[ $src_hash != $dst_hash ]]; then
+        echo "Uploading $src → $dst"
+        aws s3 cp "$src" "$dst"
 
-    if ! "$bin"/notify-slack "Updated $dst available."; then
-        echo "Notifying Slack failed, but exiting with success anyway."
+        if ! "$bin"/notify-slack "Updated $dst available."; then
+            echo "Notifying Slack failed, but exiting with success anyway."
+        fi
+    else
+        echo "Files are identical, skipping upload"
     fi
-else
-    echo "Files are identical, skipping upload"
-fi
+}
+
+main "$@"
